# -*- coding: utf-8 -*-
"""task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MYNtwKxDH3vSqRp-WOuEy5ptZO7DgqR4
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df = pd.read_csv(url)
df.head()

print(df.describe())
print(df.info())

print(df.isnull().sum())

df[['Age','Fare']].hist(figsize=(8,4))
plt.show()

# box plot for outliners
sns.boxplot(data=df[['Age','Fare']])
plt.title("Age and Fare Boxplots")
plt.show()

#Correlation Matrix
plt.figure(figsize=(6,5))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.show()

#6. Pairplot
sns.pairplot(df[['Survived','Pclass','Age','Fare']], hue='Survived')
plt.show()

# 8. Basic Inference Example
surv_rate = df['Survived'].mean()
print(f"Overall survival rate: {surv_rate:.2%}")

